import { AlertTriangle, ArrowLeft, Check, Info } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useNutrition } from '../state/NutritionContext';
import { formatKcal, formatMacro, signed } from '../ui/format';

export function ProposalPage() {
  const { state, rejectProposal, acceptProposal } = useNutrition();
  const navigate = useNavigate();
  const proposal = state?.pendingProposal;
  if (!state || !proposal) return <main className="page"><div className="empty-state"><Info /><h1>No hay una propuesta pendiente</h1><p>Tu plan vigente se mantiene sin cambios.</p><button className="button button--primary" onClick={() => navigate('/')}>Volver a hoy</button></div></main>;
  return <main className="page proposal-page">
    <button className="back-link" onClick={() => navigate('/')}><ArrowLeft /> Volver</button>
    <header className="page-heading"><p className="eyebrow">Propuesta sin aplicar</p><h1>Ajuste para el resto del día</h1><p>{proposal.reason}. Solo se incluyen comidas futuras pendientes y nada cambia hasta que confirmes.</p></header>
    {proposal.warnings.map((warning) => <div className="warning-banner" key={warning}><AlertTriangle /><span>{warning}</span></div>)}
    <section className="remaining-card"><div><p className="eyebrow">Macros restantes</p><h2>Lo que queda disponible hoy</h2></div><div className="remaining-macros"><span><strong>{formatMacro(proposal.remaining.protein)}</strong>Proteína</span><span><strong>{formatMacro(proposal.remaining.fat)}</strong>Grasa</span><span><strong>{formatMacro(proposal.remaining.carbs)}</strong>Carbohidratos</span><span><strong>{formatKcal(proposal.remaining.kcal)}</strong>Energía</span></div></section>
    <section className="proposal-list"><div className="section-heading"><div><p className="eyebrow">Comparación</p><h2>Comidas que podrían cambiar</h2></div></div>{proposal.adjustments.length === 0 ? <div className="empty-inline"><Info /><strong>No quedan comidas pendientes</strong><span>La propuesta no modifica registros existentes.</span></div> : proposal.adjustments.map((adjustment) => { const meal = state.plan.meals.find((item) => item.id === adjustment.mealId)!; return <article className="proposal-card" key={adjustment.mealId}><div className="proposal-card__head"><div><span className="tag">{meal.time}</span><h3>{meal.name}</h3></div><span className={adjustment.exact ? 'fit-badge' : 'fit-badge fit-badge--approx'}>{adjustment.exact ? 'Ajuste cercano' : 'Referencia aproximada'}</span></div><div className="comparison-columns"><div><small>Plan original</small><strong>{formatKcal(adjustment.originalMacros.kcal)}</strong><span>{formatMacro(adjustment.originalMacros.protein)} P · {formatMacro(adjustment.originalMacros.fat)} G · {formatMacro(adjustment.originalMacros.carbs)} C</span></div><div className="comparison-arrow">→</div><div className="proposed"><small>Propuesta</small><strong>{formatKcal(adjustment.proposedMacros.kcal)}</strong><span>{formatMacro(adjustment.proposedMacros.protein)} P · {formatMacro(adjustment.proposedMacros.fat)} G · {formatMacro(adjustment.proposedMacros.carbs)} C</span></div></div><div className="proposal-difference"><span>Diferencia de energía</span><strong>{signed(adjustment.proposedMacros.kcal - adjustment.originalMacros.kcal, 'kcal')}</strong></div><div className="equivalent-chips">{Object.entries(adjustment.equivalents).map(([groupId, value]) => <span key={groupId}>{state.smaeGroups.find((group) => group.id === groupId)?.group ?? groupId}: {value} eq</span>)}</div>{!adjustment.exact && <p className="approx-note"><Info size={16}/> No fue posible crear porciones exactas; se conservan los macros como referencia.</p>}</article>; })}</section>
    <div className="sticky-actions"><button className="button button--secondary" onClick={() => { rejectProposal(); navigate('/'); }}>Mantener plan original</button><button className="button button--primary" disabled={!proposal.adjustments.length} onClick={() => { acceptProposal(); navigate('/'); }}><Check /> Aplicar propuesta</button></div>
  </main>;
}
