import { ChevronDown, Clock3, Info, Plus, Scale, Utensils } from 'lucide-react';
import { useState } from 'react';
import { recipeMacros } from '../domain/calculations';
import { useNutrition } from '../state/NutritionContext';
import { formatKcal, formatMacro, numberFormat } from '../ui/format';

export function RecipesPage() {
  const { state } = useNutrition();
  const [portions, setPortions] = useState<Record<string, number>>({});
  const [expanded, setExpanded] = useState<string>('dinner-shake');
  if (!state) return null;
  return <main className="page recipes-page"><header className="page-heading"><p className="eyebrow">Alternativas del plan</p><h1>Recetas</h1><p>Consulta ingredientes y escala las cantidades automáticamente.</p></header><div className="recipe-grid">{state.recipes.map((recipe) => { const servingCount = portions[recipe.id] ?? 1; const macros = recipeMacros(recipe, state.foods, servingCount); const open = expanded === recipe.id; return <article className="recipe-card" key={recipe.id}><div className="recipe-visual"><span><Utensils /></span><div className="recipe-leaf"/></div><div className="recipe-card__body"><div className="recipe-meta"><span className={recipe.mode === 'manual' ? 'data-badge data-badge--manual' : 'data-badge data-badge--calculated'}>{recipe.mode === 'manual' ? 'Información manual' : 'Receta calculada'}</span><span><Clock3/> 5 min</span></div><h2>{recipe.name}</h2><p>{recipe.description}</p><div className="recipe-macro-row"><span><strong>{formatKcal(macros.kcal)}</strong>Energía</span><span><strong>{formatMacro(macros.protein)}</strong>Proteína</span><span><strong>{formatMacro(macros.carbs)}</strong>Carbos</span></div><div className="serving-control"><span>Porciones a registrar</span><div><button onClick={() => setPortions((current) => ({ ...current, [recipe.id]: Math.max(0.5, servingCount - 0.5) }))}>−</button><strong>{numberFormat.format(servingCount)}</strong><button onClick={() => setPortions((current) => ({ ...current, [recipe.id]: servingCount + 0.5 }))}>+</button></div></div><button className="ingredients-toggle" aria-expanded={open} onClick={() => setExpanded(open ? '' : recipe.id)}>Ver ingredientes y equivalentes <ChevronDown /></button>{open && <div className="ingredients-list">{recipe.mode === 'manual' ? <p className="approx-note"><Info/> Los macros fueron capturados sin desglose; no se pueden recalcular equivalentes exactos.</p> : recipe.ingredients.map((ingredient) => { const food = state.foods.find((item) => item.id === ingredient.foodId); return <div key={ingredient.id}><span>{food?.name}</span><strong>{numberFormat.format(ingredient.quantity * servingCount / recipe.servings)} {ingredient.unit}</strong></div>; })}<div className="smae-note"><Scale/><span><strong>Equivalentes SMAE aproximados</strong>{recipe.smaeNote}</span></div></div>}<button className="button button--secondary button--full" disabled title="Añádela desde el registro de una comida"><Plus/> Añadir desde una comida</button></div></article>; })}</div></main>;
}
